name: Build

on:
  workflow_dispatch:
  push:
    branches: ["develop", "release-please--branches--master"]
  pull_request:
    branches: ["master", "develop"]

env:
  GLOBAL_JSON_PATH: "./src/global.json"
  PROJECT_PATH: "./src/Servus.sln"
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: >
          dotnet build
          --configuration Release
          --no-restore
          ${{ env.PROJECT_PATH }}

      - name: Run tests
        working-directory: "./src"
        run: >
          dotnet test
          --configuration Release
          --no-ansi
          --no-build
          --coverage
          --coverage-output-format xml
          --solution Servus.sln
          --results-directory ./TestResults